<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f868c743-fd44-40e2-98fe-8426f5a2f373</testSuiteGuid>
   <testCaseLink>
      <guid>51bf8500-c78c-4aed-a52a-7a2dabafae56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>72844347-b035-4d31-8452-29f2534eda44</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/databinding</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>72844347-b035-4d31-8452-29f2534eda44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>423d11b7-07dd-4f58-a9b5-e71b34dcac27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72844347-b035-4d31-8452-29f2534eda44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>81ca76f2-3e32-4191-8279-b70462acd192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>72844347-b035-4d31-8452-29f2534eda44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9fc9562a-09ce-46c1-a02b-8b51ecef2bab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20f741e6-70b6-4313-8e21-7dfbfe272597</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/book appoinment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8ce6e87f-6873-437a-a380-29f279d71fb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Chek</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>eb3346dc-f6f0-4d06-862b-2256b5343c9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
